change: Display percentage symbol after value on surcharge page.
flat-peak/flatpeak-connect-web pull request #20
Opened 2024-07-11 19:21 UTC by Alert1437

Add possibility to remove numbers from defaults.

2024-07-11 23:00 UTC, alexalenberg approved these changes

2024-07-12 07:26 UTC, alexalenberg requested changes
Multiple build errors

2024-07-12 08:14 UTC, Alert1437 commented
> Multiple build errors

fixed and merge conflicts resolved

2024-07-14 11:05 UTC, alexalenberg approved these changes

2024-07-14 11:05 UTC, merged